export const sideBarLinks = [
  {
    title: "Dashboard",
    icon: "LayoutDashboard",
    link: "/",
  },
  {
    title: "Employees",
    icon: "Contact",
    link: "/all-employees",
  },
  {
    title: "My Task",
    icon: "Table",
    link: "/task",
  },
  {
    title: "Attendance",
    icon: "FileChartColumn",
    link: "/attendance",
  },
  {
    title: "Payroll",
    icon: "CircleDollarSign",
    link: "/payroll",
  },
  {
    title: "Leaves",
    icon: "BriefcaseBusiness",
    link: "/leaves",
  },
  {
    title: "Holidays",
    icon: "CalendarCheck2",
    link: "/holidays",
  },
  {
    title: "Settings",
    icon: "Settings",
    link: "/settings",
  },
];

export const notificationData = [
  {
    name: "Ralph Edwards",
    time: "2 min Ago.",
    order: "Ordered 3 meals and 1 drink.",
    image: "/bag-happy.png",
    unread: true,
    items: [
      {
        quantity: "1x",
        name: "Fish and Chips with sausage vegetarian",
        price: "$12.00",
      },
      {
        quantity: "1x",
        name: "Fish and Chips with sausage vegetarian",
        price: "$12.00",
      },
      {
        quantity: "1x",
        name: "Fish and Chips with sausage vegetarian",
        price: "$12.00",
      },
    ],
  },
  {
    name: "Ralph Edwards",
    time: "2 min Ago.",
    order: "Ordered 3 meals and 1 drink.",
    image: "/clipboard-close.png",
    unread: true,
    items: [
      {
        quantity: "1x",
        name: "Fish and Chips with sausage vegetarian",
        price: "$12.00",
      },
      {
        quantity: "1x",
        name: "Fish and Chips with sausage vegetarian",
        price: "$12.00",
      },
      {
        quantity: "1x",
        name: "Fish and Chips with sausage vegetarian",
        price: "$12.00",
      },
    ],
  },
  {
    name: "Ralph Edwards",
    time: "2 min Ago.",
    order: "Ordered 3 meals and 1 drink.",
    image: "/bag-happy.png",
    unread: false,
    items: [
      {
        quantity: "1x",
        name: "Fish and Chips with sausage vegetarian",
        price: "$12.00",
      },
      {
        quantity: "1x",
        name: "Fish and Chips with sausage vegetarian",
        price: "$12.00",
      },
      {
        quantity: "1x",
        name: "Fish and Chips with sausage vegetarian",
        price: "$12.00",
      },
    ],
  },
  {
    name: "Ralph Edwards",
    time: "2 min Ago.",
    order: "Ordered 3 meals and 1 drink.",
    image: "/bag-happy.png",
    unread: false,
    items: [
      {
        quantity: "1x",
        name: "Fish and Chips with sausage vegetarian",
        price: "$12.00",
      },
      {
        quantity: "1x",
        name: "Fish and Chips with sausage vegetarian",
        price: "$12.00",
      },
      {
        quantity: "1x",
        name: "Fish and Chips with sausage vegetarian",
        price: "$12.00",
      },
    ],
  },
];

export const statsData = [
  {
    title: "Total Employee",
    amount: 560,
    orders: 28,
    percentage: 28,
    icon: "Contact",
    bgColor: "primary-50",
    lastUpdated: "July 14 , 2023",
  },
  {
    title: "Total Departments",
    amount: 10,
    orders: 10,
    percentage: -28,
    icon: "Table",
    bgColor: "primary-100",
    lastUpdated: "July 14 , 2023",
  },
  {
    title: "Today Attendance",
    amount: 20,
    orders: 14,
    percentage: 56,
    icon: "FileChartColumn",
    bgColor: "default-100",
    lastUpdated: "July 14 , 2023",
  },
  {
    title: "Total Payroll",
    amount: 28033,
    orders: 16,
    percentage: -10,
    icon: "CircleDollarSign",
    bgColor: "success-100",
    lastUpdated: "July 14 , 2023",
  },
];

export const columns = [
  { name: "ID", uid: "id", sortable: true },
  { name: "Employee Name", uid: "name", sortable: true },
  { name: "Department", uid: "department", sortable: true },
  { name: "Designation", uid: "designation", sortable: true },
  { name: "Job Type", uid: "jobType" },
  { name: "Status", uid: "status", sortable: true },
  { name: "Actions", uid: "actions" },
];

export const attendanceColumn = [
  {
    name: "Date",
    uid: "date",
    sortable: true,
  },
  {
    name: "Check In",
    uid: "checkIn",
  },
  {
    name: "Check Out",
    uid: "checkOut",
  },
  {
    name: "Break",
    uid: "break",
  },
  {
    name: "Working Hours",
    uid: "workingHours",
  },
  {
    name: "Status",
    uid: "status",
  },
];

export const attendance = [
  {
    date: "July 01, 2023",
    checkIn: "09:28 AM",
    checkOut: "07:00 PM",
    break: "00:30 Min",
    workingHours: "09:02 Hrs",
    status: "onTime",
  },
  {
    date: "July 02, 2023",
    checkIn: "09:15 AM",
    checkOut: "06:45 PM",
    break: "00:45 Min",
    workingHours: "08:45 Hrs",
    status: "onTime",
  },
  {
    date: "July 03, 2023",
    checkIn: "09:50 AM",
    checkOut: "07:30 PM",
    break: "01:00 Hr",
    workingHours: "08:40 Hrs",
    status: "late",
  },
  {
    date: "July 04, 2023",
    checkIn: "09:00 AM",
    checkOut: "06:30 PM",
    break: "00:30 Min",
    workingHours: "09:00 Hrs",
    status: "onTime",
  },
  {
    date: "July 05, 2023",
    checkIn: "08:45 AM",
    checkOut: "06:15 PM",
    break: "00:45 Min",
    workingHours: "08:45 Hrs",
    status: "onTime",
  },
  {
    date: "July 06, 2023",
    checkIn: "09:05 AM",
    checkOut: "07:05 PM",
    break: "00:30 Min",
    workingHours: "09:30 Hrs",
    status: "onTime",
  },
  {
    date: "July 07, 2023",
    checkIn: "09:30 AM",
    checkOut: "07:15 PM",
    break: "01:00 Hr",
    workingHours: "08:45 Hrs",
    status: "late",
  },
  {
    date: "July 08, 2023",
    checkIn: "09:20 AM",
    checkOut: "06:50 PM",
    break: "00:30 Min",
    workingHours: "08:50 Hrs",
    status: "onTime",
  },
  {
    date: "July 09, 2023",
    checkIn: "09:10 AM",
    checkOut: "06:40 PM",
    break: "00:45 Min",
    workingHours: "08:45 Hrs",
    status: "onTime",
  },
  {
    date: "July 10, 2023",
    checkIn: "09:25 AM",
    checkOut: "07:00 PM",
    break: "00:30 Min",
    workingHours: "09:05 Hrs",
    status: "onTime",
  },
  {
    date: "July 01, 2023",
    checkIn: "09:28 AM",
    checkOut: "07:00 PM",
    break: "00:30 Min",
    workingHours: "09:02 Hrs",
    status: "onTime",
  },
  {
    date: "July 02, 2023",
    checkIn: "09:15 AM",
    checkOut: "06:45 PM",
    break: "00:45 Min",
    workingHours: "08:45 Hrs",
    status: "onTime",
  },
  {
    date: "July 03, 2023",
    checkIn: "09:50 AM",
    checkOut: "07:30 PM",
    break: "01:00 Hr",
    workingHours: "08:40 Hrs",
    status: "late",
  },
  {
    date: "July 04, 2023",
    checkIn: "09:00 AM",
    checkOut: "06:30 PM",
    break: "00:30 Min",
    workingHours: "09:00 Hrs",
    status: "onTime",
  },
];

export const attendanceStatusOption = [
  { name: "On Time", uid: "onTime", color: "success" },
  { name: "Late", uid: "late", color: "danger" },
];

export const statusOptions = [
  { name: "Permanent", uid: "permanent", color: "primary" },
  { name: "Intern", uid: "intern", color: "success" },
  { name: "Notice Period", uid: "notice-period", color: "danger" },
];

export const users = [
  {
    id: 1,
    name: "Tony Reichert",
    role: "CEO",
    team: "Management",
    status: "permanent",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
    department: "Executive",
    designation: "Chief Executive Officer",
    jobType: "in-office",
  },
  {
    id: 2,
    name: "Zoey Lang",
    role: "Tech Lead",
    team: "Development",
    status: "intern",
    age: "25",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "zoey.lang@example.com",
    department: "Engineering",
    designation: "Technical Lead",
    jobType: "remote",
  },
  {
    id: 3,
    name: "Jane Fisher",
    role: "Sr. Dev",
    team: "Development",
    status: "permanent",
    age: "22",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "jane.fisher@example.com",
    department: "Engineering",
    designation: "Senior Developer",
    jobType: "hybrid",
  },
  {
    id: 4,
    name: "William Howard",
    role: "C.M.",
    team: "Marketing",
    status: "notice-period",
    age: "28",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    email: "william.howard@example.com",
    department: "Marketing",
    designation: "Campaign Manager",
    jobType: "in-office",
  },
  {
    id: 5,
    name: "Kristen Copper",
    role: "S. Manager",
    team: "Sales",
    status: "permanent",
    age: "24",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "kristen.cooper@example.com",
    department: "Sales",
    designation: "Sales Manager",
    jobType: "remote",
  },
  {
    id: 6,
    name: "Brian Kim",
    role: "P. Manager",
    team: "Management",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "brian.kim@example.com",
    status: "permanent",
    department: "Project Management",
    designation: "Project Manager",
    jobType: "hybrid",
  },
  {
    id: 7,
    name: "Michael Hunt",
    role: "Designer",
    team: "Design",
    status: "intern",
    age: "27",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
    email: "michael.hunt@example.com",
    department: "Creative",
    designation: "Graphic Designer",
    jobType: "remote",
  },
  {
    id: 8,
    name: "Samantha Brooks",
    role: "HR Manager",
    team: "HR",
    status: "permanent",
    age: "31",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
    email: "samantha.brooks@example.com",
    department: "Human Resources",
    designation: "Human Resources Manager",
    jobType: "in-office",
  },
  {
    id: 9,
    name: "Frank Harrison",
    role: "F. Manager",
    team: "Finance",
    status: "notice-period",
    age: "33",
    avatar: "https://i.pravatar.cc/150?img=4",
    email: "frank.harrison@example.com",
    department: "Finance",
    designation: "Finance Manager",
    jobType: "hybrid",
  },
  {
    id: 10,
    name: "Emma Adams",
    role: "Ops Manager",
    team: "Operations",
    status: "permanent",
    age: "35",
    avatar: "https://i.pravatar.cc/150?img=5",
    email: "emma.adams@example.com",
    department: "Operations",
    designation: "Operations Manager",
    jobType: "in-office",
  },
  {
    id: 11,
    name: "Brandon Stevens",
    role: "Jr. Dev",
    team: "Development",
    status: "permanent",
    age: "22",
    avatar: "https://i.pravatar.cc/150?img=8",
    email: "brandon.stevens@example.com",
    department: "Engineering",
    designation: "Junior Developer",
    jobType: "remote",
  },
  {
    id: 12,
    name: "Megan Richards",
    role: "P. Manager",
    team: "Product",
    status: "intern",
    age: "28",
    avatar: "https://i.pravatar.cc/150?img=10",
    email: "megan.richards@example.com",
    department: "Product",
    designation: "Product Manager",
    jobType: "hybrid",
  },
  {
    id: 13,
    name: "Oliver Scott",
    role: "S. Manager",
    team: "Security",
    status: "permanent",
    age: "37",
    avatar: "https://i.pravatar.cc/150?img=12",
    email: "oliver.scott@example.com",
    department: "Security",
    designation: "Security Manager",
    jobType: "in-office",
  },
  {
    id: 14,
    name: "Grace Allen",
    role: "M. Specialist",
    team: "Marketing",
    status: "permanent",
    age: "30",
    avatar: "https://i.pravatar.cc/150?img=16",
    email: "grace.allen@example.com",
    department: "Marketing",
    designation: "Marketing Specialist",
    jobType: "remote",
  },
  {
    id: 15,
    name: "Noah Carter",
    role: "IT Specialist",
    team: "I. Technology",
    status: "intern",
    age: "31",
    avatar: "https://i.pravatar.cc/150?img=15",
    email: "noah.carter@example.com",
    department: "Information Technology",
    designation: "IT Specialist",
    jobType: "hybrid",
  },
  {
    id: 16,
    name: "Ava Perez",
    role: "Manager",
    team: "Sales",
    status: "permanent",
    age: "29",
    avatar: "https://i.pravatar.cc/150?img=20",
    email: "ava.perez@example.com",
    department: "Sales",
    designation: "Sales Manager",
    jobType: "in-office",
  },
  {
    id: 17,
    name: "Liam Johnson",
    role: "Data Analyst",
    team: "Analysis",
    status: "permanent",
    age: "28",
    avatar: "https://i.pravatar.cc/150?img=33",
    email: "liam.johnson@example.com",
    department: "Data Analysis",
    designation: "Data Analyst",
    jobType: "remote",
  },
  {
    id: 18,
    name: "Sophia Taylor",
    role: "QA Analyst",
    team: "Testing",
    status: "permanent",
    age: "27",
    avatar: "https://i.pravatar.cc/150?img=29",
    email: "sophia.taylor@example.com",
    department: "Quality Assurance",
    designation: "QA Analyst",
    jobType: "hybrid",
  },
  {
    id: 19,
    name: "Lucas Harris",
    role: "Administrator",
    team: "Information Technology",
    status: "intern",
    age: "32",
    avatar: "https://i.pravatar.cc/150?img=50",
    email: "lucas.harris@example.com",
    department: "Information Technology",
    designation: "System Administrator",
    jobType: "in-office",
  },
  {
    id: 20,
    name: "Mia Robinson",
    role: "Coordinator",
    team: "Operations",
    status: "permanent",
    age: "26",
    avatar: "https://i.pravatar.cc/150?img=45",
    email: "mia.robinson@example.com",
    department: "Operations",
    designation: "Operations Coordinator",
    jobType: "remote",
  },
];

export const tab = [
  {
    title: "Personal Information",
    icon: "ContactRound",
  },
  {
    title: "Professional Information",
    icon: "BriefcaseBusiness",
  },
  {
    title: "Documents",
    icon: "FolderClosed",
  },
  {
    title: "Account Access",
    icon: "LockKeyholeOpen",
  },
];

export const personalField = [
  {
    id: "firstName",
    title: "First Name",
    type: "text",
  },
  {
    id: "lastName",
    title: "Last Name",
    type: "text",
  },
  {
    id: "email",
    title: "Email Address",
    type: "email",
  },
  {
    id: "phone",
    title: "Phone",
    type: "number",
  },
  {
    id: "dob",
    title: "Date of Birth",
    type: "date",
  },
  {
    id: "address",
    title: "Address",
    type: "text",
  },
  {
    id: "city",
    title: "City",
    type: "text",
  },
  {
    id: "state",
    title: "State",
    type: "text",
  },
  {
    id: "zip",
    title: "Zip Code",
    type: "number",
  },
  {
    id: "maritalstatus",
    title: "Marital Status",
    type: "dropdown",
    data: [
      { id: "single", title: "Single" },
      { id: "married", title: "Married" },
      { id: "divorced", title: "Divorced" },
    ],
  },
  {
    id: "gender",
    title: "Gender",
    type: "dropdown",
    data: [
      { id: "male", title: "Male" },
      { id: "female", title: "Female" },
    ],
  },
  {
    id: "nationality",
    title: "Nationality",
    type: "dropdown",
    data: [
      { id: "indian", title: "Indian" },
      { id: "american", title: "American" },
      { id: "canadian", title: "Canadian" },
    ],
  },
];

export const professionalField = [
  {
    id: "employeeId",
    title: "Employee ID",
    type: "text",
  },
  {
    id: "username",
    title: "User Name",
    type: "text",
  },
  {
    id: "employeeType",
    title: "Employee Type",
    type: "dropdown",
    data: [
      { id: "permanent", title: "Permanent" },
      { id: "intern", title: "Intern" },
      { id: "noticePeriod", title: "Notice Period" },
    ],
  },
  {
    id: "email",
    title: "Email Address",
    type: "email",
  },
  {
    id: "department",
    title: "Department",
    type: "dropdown",
    data: [
      { id: "engineering", title: "Engineering" },
      { id: "marketing", title: "Marketing" },
      { id: "sales", title: "Sales" },
      { id: "humanResources", title: "Human Resources" },
      { id: "finance", title: "Finance" },
      { id: "operations", title: "Operations" },
      { id: "creative", title: "Creative" },
      { id: "product", title: "Product" },
      { id: "security", title: "Security" },
      { id: "informationTechnology", title: "Information Technology" },
    ],
  },
  {
    id: "designation",
    title: "Enter Designation",
    type: "text",
  },
  {
    id: "workingDays",
    title: "Working Days",
    type: "dropdown",
    data: [
      { id: "mondayToFriday", title: "Monday to Friday" },
      { id: "mondayToSaturday", title: "Monday to Saturday" },
      { id: "mondayToSunday", title: "Monday to Sunday" },
    ],
  },
  {
    id: "joiningDate",
    title: "Joining Date",
    type: "date",
  },
  {
    id: "jobType",
    title: "Job Type",
    type: "dropdown",
    data: [
      { id: "inOffice", title: "In-Office" },
      { id: "remote", title: "Remote" },
      { id: "hybrid", title: "Hybrid" },
    ],
  },
  {
    id: "reportingManager",
    title: "Reporting Manager",
    type: "dropdown",
    data: [
      { id: "tonyReichert", title: "Tony Reichert" },
      { id: "zoeyLang", title: "Zoey Lang" },
      { id: "janeFisher", title: "Jane Fisher" },
      { id: "williamHoward", title: "William Howard" },
      { id: "kristenCopper", title: "Kristen Copper" },
      { id: "brianKim", title: "Brian Kim" },
      { id: "michaelHunt", title: "Michael Hunt" },
      { id: "samanthaBrooks", title: "Samantha Brooks" },
      { id: "frankHarrison", title: "Frank Harrison" },
      { id: "emmaAdams", title: "Emma Adams" },
      { id: "brandonStevens", title: "Brandon Stevens" },
      { id: "meganRichards", title: "Megan Richards" },
      { id: "oliverScott", title: "Oliver Scott" },
      { id: "graceAllen", title: "Grace Allen" },
      { id: "noahCarter", title: "Noah Carter" },
      { id: "avaPerez", title: "Ava Perez" },
      { id: "liamJohnson", title: "Liam Johnson" },
      { id: "sophiaTaylor", title: "Sophia Taylor" },
      { id: "lucasHarris", title: "Lucas Harris" },
      { id: "miaRobinson", title: "Mia Robinson" },
    ],
  },
  {
    id: "officeLocation",
    title: "Office Location",
    type: "dropdown",
    data: [
      { id: "newYork", title: "New York" },
      { id: "losAngeles", title: "Los Angeles" },
      { id: "chicago", title: "Chicago" },
      { id: "houston", title: "Houston" },
      { id: "phoenix", title: "Phoenix" },
      { id: "philadelphia", title: "Philadelphia" },
      { id: "sanAntonio", title: "San Antonio" },
      { id: "sanDiego", title: "San Diego" },
      { id: "dallas", title: "Dallas" },
      { id: "sanJose", title: "San Jose" },
      { id: "austin", title: "Austin" },
      { id: "jacksonville", title: "Jacksonville" },
      { id: "fortWorth", title: "Fort Worth" },
      { id: "columbus", title: "Columbus" },
      { id: "charlotte", title: "Charlotte" },
      { id: "indianapolis", title: "Indianapolis" },
      { id: "sanFrancisco", title: "San Francisco" },
      { id: "seattle", title: "Seattle" },
      { id: "denver", title: "Denver" },
      { id: "washington", title: "Washington" },
    ],
  },
];

export const socialField = [
  {
    id: "instagram",
    title: "Instagram",
    type: "text",
  },
  {
    id: "twitter",
    title: "Twitter",
    type: "text",
  },
  {
    id: "linkedin",
    title: "LinkedIn",
    type: "text",
  },
  {
    id: "github",
    title: "Github",
    type: "text",
  },
];

export const projectStatusOptions = [
  { name: "Completed", uid: "completed", color: "success" },
  { name: "In - Progress", uid: "inProgress", color: "warning" },
  { name: "Pending", uid: "pending", color: "danger" },
];

export const projectColumn = [
  {
    name: "Sr. No.",
    uid: "serialNumber",
    sortable: true,
  },
  {
    name: "Project Name",
    uid: "projectName",
  },
  {
    name: "Start Date",
    uid: "startDate",
  },
  {
    name: "Finish Date",
    uid: "finishDate",
  },
  {
    name: "Status",
    uid: "status",
  },
];

export const projectData = [
  {
    serialNumber: "1",
    projectName: "Hingutasan Web Development",
    startDate: "Feb 12, 2023",
    finishDate: "Mar 05, 2023",
    status: "completed",
  },
  {
    serialNumber: "2",
    projectName: "Alpha Mobile App",
    startDate: "Jan 10, 2023",
    finishDate: "Feb 20, 2023",
    status: "completed",
  },
  {
    serialNumber: "3",
    projectName: "Beta Testing Suite",
    startDate: "Mar 01, 2023",
    finishDate: "Apr 15, 2023",
    status: "inProgress",
  },
  {
    serialNumber: "4",
    projectName: "Gamma API Integration",
    startDate: "Apr 05, 2023",
    finishDate: "May 10, 2023",
    status: "pending",
  },
  {
    serialNumber: "5",
    projectName: "Delta UX Design",
    startDate: "Feb 20, 2023",
    finishDate: "Mar 30, 2023",
    status: "completed",
  },
  {
    serialNumber: "6",
    projectName: "Epsilon Database Migration",
    startDate: "Mar 15, 2023",
    finishDate: "Apr 25, 2023",
    status: "inProgress",
  },
  {
    serialNumber: "7",
    projectName: "Zeta Cloud Deployment",
    startDate: "Jan 25, 2023",
    finishDate: "Feb 28, 2023",
    status: "completed",
  },
  {
    serialNumber: "8",
    projectName: "Eta Security Audit",
    startDate: "Mar 10, 2023",
    finishDate: "Apr 20, 2023",
    status: "pending",
  },
  {
    serialNumber: "9",
    projectName: "Theta Performance Optimization",
    startDate: "Feb 05, 2023",
    finishDate: "Mar 15, 2023",
    status: "completed",
  },
  {
    serialNumber: "10",
    projectName: "Iota Feature Development",
    startDate: "Apr 01, 2023",
    finishDate: "May 05, 2023",
    status: "inProgress",
  },
  {
    serialNumber: "11",
    projectName: "Kappa Code Refactoring",
    startDate: "Jan 15, 2023",
    finishDate: "Feb 25, 2023",
    status: "completed",
  },
  {
    serialNumber: "12",
    projectName: "Lambda User Testing",
    startDate: "Mar 20, 2023",
    finishDate: "Apr 30, 2023",
    status: "pending",
  },
  {
    serialNumber: "13",
    projectName: "Mu Documentation",
    startDate: "Feb 10, 2023",
    finishDate: "Mar 20, 2023",
    status: "completed",
  },
  {
    serialNumber: "14",
    projectName: "Nu Bug Fixing",
    startDate: "Apr 10, 2023",
    finishDate: "May 15, 2023",
    status: "inProgress",
  },
  {
    serialNumber: "15",
    projectName: "Xi Release Management",
    startDate: "Jan 05, 2023",
    finishDate: "Feb 15, 2023",
    status: "completed",
  },
  {
    serialNumber: "16",
    projectName: "Omicron Client Feedback",
    startDate: "Mar 25, 2023",
    finishDate: "Apr 25, 2023",
    status: "pending",
  },
];

export const leaveStatusOptions = [
  { name: "Approved", uid: "approved", color: "success" },
  { name: "Pending", uid: "pending", color: "warning" },
  { name: "Reject", uid: "reject", color: "danger" },
];

export const leaveColumn = [
  {
    name: "Date",
    uid: "date",
    sortable: true,
  },
  {
    name: "Duration",
    uid: "duration",
  },
  {
    name: "Days",
    uid: "days",
  },
  {
    name: "Reporting Manager",
    uid: "reportingManager",
  },
  {
    name: "Status",
    uid: "status",
  },
];

export const leaveData = [
  {
    date: "July 01, 2023",
    duration: "July 05 - July 08",
    days: "3 Days",
    reportingManager: "Tony Reichert",
    status: "approved",
  },
  {
    date: "July 10, 2023",
    duration: "July 12 - July 14",
    days: "2 Days",
    reportingManager: "Sarah Connor",
    status: "pending",
  },
  {
    date: "August 01, 2023",
    duration: "August 05 - August 07",
    days: "3 Days",
    reportingManager: "John Doe",
    status: "reject",
  },
  {
    date: "August 15, 2023",
    duration: "August 20 - August 22",
    days: "3 Days",
    reportingManager: "Jane Smith",
    status: "approved",
  },
  {
    date: "September 01, 2023",
    duration: "September 05 - September 07",
    days: "3 Days",
    reportingManager: "Tony Reichert",
    status: "pending",
  },
  {
    date: "September 10, 2023",
    duration: "September 12 - September 14",
    days: "2 Days",
    reportingManager: "Sarah Connor",
    status: "approved",
  },
  {
    date: "October 01, 2023",
    duration: "October 05 - October 07",
    days: "3 Days",
    reportingManager: "John Doe",
    status: "reject",
  },
  {
    date: "October 15, 2023",
    duration: "October 20 - October 22",
    days: "3 Days",
    reportingManager: "Jane Smith",
    status: "approved",
  },
  {
    date: "November 01, 2023",
    duration: "November 05 - November 07",
    days: "3 Days",
    reportingManager: "Tony Reichert",
    status: "pending",
  },
  {
    date: "November 10, 2023",
    duration: "November 12 - November 14",
    days: "2 Days",
    reportingManager: "Sarah Connor",
    status: "approved",
  },
  {
    date: "December 01, 2023",
    duration: "December 05 - December 07",
    days: "3 Days",
    reportingManager: "John Doe",
    status: "reject",
  },
  {
    date: "December 15, 2023",
    duration: "December 20 - December 22",
    days: "3 Days",
    reportingManager: "Jane Smith",
    status: "approved",
  },
  {
    date: "January 01, 2024",
    duration: "January 05 - January 07",
    days: "3 Days",
    reportingManager: "Tony Reichert",
    status: "pending",
  },
  {
    date: "January 10, 2024",
    duration: "January 12 - January 14",
    days: "2 Days",
    reportingManager: "Sarah Connor",
    status: "approved",
  },
  {
    date: "February 01, 2024",
    duration: "February 05 - February 07",
    days: "3 Days",
    reportingManager: "John Doe",
    status: "reject",
  },
  {
    date: "February 15, 2024",
    duration: "February 20 - February 22",
    days: "3 Days",
    reportingManager: "Jane Smith",
    status: "approved",
  },
];

export const attendancePageColumn = [
  {
    name: "Employee Name",
    uid: "name",
    sortable: true,
  },
  {
    name: "Designation",
    uid: "designation",
  },
  {
    name: "Department",
    uid: "department",
  },
  {
    name: "Type",
    uid: "type",
  },
  {
    name: "Check In Time",
    uid: "checkInTime",
  },
  {
    name: "Check Out Time",
    uid: "checkOutTime",
  },
  {
    name: "Status",
    uid: "status",
  },
];

export const usersAttendanceData = [
  {
    id: 1,
    name: "Tony Reichert",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    department: "Executive",
    checkInTime: "09:00 AM",
    checkOutTime: "06:00 PM",
    team: "Management",
    designation: "Chief Executive Officer",
    type: "in-office",
    status: "onTime",
  },
  {
    id: 2,
    name: "Zoey Lang",
    checkInTime: "09:15 AM",
    checkOutTime: "06:15 PM",
    team: "Development",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    department: "Engineering",
    designation: "Technical Lead",
    type: "remote",
    status: "late",
  },
  {
    id: 3,
    name: "Jane Fisher",
    checkInTime: "09:30 AM",
    checkOutTime: "06:30 PM",
    team: "Development",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    department: "Engineering",
    designation: "Senior Developer",
    type: "hybrid",
    status: "late",
  },
  {
    id: 4,
    name: "William Howard",
    checkInTime: "09:45 AM",
    checkOutTime: "06:45 PM",
    team: "Marketing",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    department: "Marketing",
    designation: "Campaign Manager",
    type: "in-office",
    status: "late",
  },
  {
    id: 5,
    name: "Kristen Copper",
    checkInTime: "10:00 AM",
    checkOutTime: "07:00 PM",
    team: "Sales",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    department: "Sales",
    designation: "Sales Manager",
    type: "remote",
    status: "late",
  },
  {
    id: 6,
    name: "Brian Kim",
    checkInTime: "10:15 AM",
    checkOutTime: "07:15 PM",
    team: "Management",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    department: "Project Management",
    designation: "Project Manager",
    type: "hybrid",
    status: "late",
  },
  {
    id: 7,
    name: "Michael Hunt",
    checkInTime: "10:30 AM",
    checkOutTime: "07:30 PM",
    team: "Design",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
    department: "Creative",
    designation: "Graphic Designer",
    type: "remote",
    status: "late",
  },
  {
    id: 8,
    name: "Samantha Brooks",
    checkInTime: "10:45 AM",
    checkOutTime: "07:45 PM",
    team: "HR",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
    department: "Human Resources",
    designation: "Human Resources Manager",
    type: "in-office",
    status: "late",
  },
  {
    id: 9,
    name: "Frank Harrison",
    checkInTime: "11:00 AM",
    checkOutTime: "08:00 PM",
    team: "Finance",
    avatar: "https://i.pravatar.cc/150?img=4",
    department: "Finance",
    designation: "Finance Manager",
    type: "hybrid",
    status: "late",
  },
  {
    id: 10,
    name: "Emma Adams",
    checkInTime: "11:15 AM",
    checkOutTime: "08:15 PM",
    team: "Operations",
    avatar: "https://i.pravatar.cc/150?img=5",
    department: "Operations",
    designation: "Operations Manager",
    type: "in-office",
    status: "late",
  },
  {
    id: 11,
    name: "Brandon Stevens",
    checkInTime: "11:30 AM",
    checkOutTime: "08:30 PM",
    team: "Development",
    avatar: "https://i.pravatar.cc/150?img=8",
    department: "Engineering",
    designation: "Junior Developer",
    type: "remote",
    status: "late",
  },
  {
    id: 12,
    name: "Megan Richards",
    checkInTime: "11:45 AM",
    checkOutTime: "08:45 PM",
    team: "Product",
    avatar: "https://i.pravatar.cc/150?img=10",
    department: "Product",
    designation: "Product Manager",
    type: "hybrid",
    status: "late",
  },
  {
    id: 13,
    name: "Oliver Scott",
    checkInTime: "12:00 PM",
    checkOutTime: "09:00 PM",
    team: "Security",
    avatar: "https://i.pravatar.cc/150?img=11",
    department: "Security",
    designation: "Security Manager",
    type: "in-office",
    status: "late",
  },
  {
    id: 14,
    name: "Sophia Turner",
    checkInTime: "12:15 PM",
    checkOutTime: "09:15 PM",
    team: "Support",
    avatar: "https://i.pravatar.cc/150?img=12",
    department: "Customer Support",
    designation: "Support Specialist",
    type: "remote",
    status: "late",
  },
  {
    id: 15,
    name: "Liam Johnson",
    checkInTime: "12:30 PM",
    checkOutTime: "09:30 PM",
    team: "IT",
    avatar: "https://i.pravatar.cc/150?img=13",
    department: "Information Technology",
    designation: "IT Manager",
    type: "hybrid",
    status: "late",
  },
  {
    id: 16,
    name: "Emily Davis",
    checkInTime: "12:45 PM",
    checkOutTime: "09:45 PM",
    team: "Legal",
    avatar: "https://i.pravatar.cc/150?img=14",
    department: "Legal",
    designation: "Legal Advisor",
    type: "in-office",
    status: "late",
  },
];

export const payrollOptions = [
  { name: "Completed", uid: "completed", color: "success" },
  { name: "Pending", uid: "pending", color: "warning" },
];

export const payrollColumn = [
  {
    name: "Employee Name",
    uid: "name",
    sortable: true,
  },
  {
    name: "CTC",
    uid: "ctc",
    money: true,
  },
  {
    name: "Designation",
    uid: "designation",
  },
  {
    name: "Department",
    uid: "department",
  },
  {
    name: "Salary Per Month",
    uid: "salaryPerMonth",
    money: true,
  },
  {
    name: "Deduction",
    uid: "deduction",
    money: true,
  },
  {
    name: "Status",
    uid: "status",
  },
];

export const payrollData = [
  {
    id: 1,
    ctc: "450000",
    salaryPerMonth: "37500",
    deduction: "5000",
    status: "completed",
    name: "Tony Reichert",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    designation: "Software Engineer",
    department: "Engineering",
    team: "Development",
  },
  {
    id: 2,
    ctc: "500000",
    salaryPerMonth: "41666",
    deduction: "6000",
    status: "pending",
    name: "Zoey Lang",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    designation: "Technical Lead",
    department: "Engineering",
    team: "Development",
  },
  {
    id: 3,
    ctc: "550000",
    salaryPerMonth: "45833",
    deduction: "7000",
    status: "completed",
    name: "Jane Fisher",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    designation: "Senior Developer",
    department: "Engineering",
    team: "Development",
  },
  {
    id: 4,
    ctc: "600000",
    salaryPerMonth: "50000",
    deduction: "8000",
    status: "pending",
    name: "William Howard",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    designation: "Campaign Manager",
    department: "Marketing",
    team: "Marketing",
  },
  {
    id: 5,
    ctc: "650000",
    salaryPerMonth: "54166",
    deduction: "9000",
    status: "completed",
    name: "Kristen Copper",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    designation: "Sales Manager",
    department: "Sales",
    team: "Sales",
  },
  {
    id: 6,
    ctc: "700000",
    salaryPerMonth: "58333",
    deduction: "10000",
    status: "pending",
    name: "Brian Kim",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    designation: "Project Manager",
    department: "Project Management",
    team: "Management",
  },
  {
    id: 7,
    ctc: "750000",
    salaryPerMonth: "62500",
    deduction: "11000",
    status: "completed",
    name: "Michael Hunt",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
    designation: "Graphic Designer",
    department: "Creative",
    team: "Design",
  },
  {
    id: 8,
    ctc: "800000",
    salaryPerMonth: "66666",
    deduction: "12000",
    status: "pending",
    name: "Samantha Brooks",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
    designation: "Human Resources Manager",
    department: "Human Resources",
    team: "HR",
  },
  {
    id: 9,
    ctc: "850000",
    salaryPerMonth: "70833",
    deduction: "13000",
    status: "completed",
    name: "Frank Harrison",
    avatar: "https://i.pravatar.cc/150?img=4",
    designation: "Finance Manager",
    department: "Finance",
    team: "Finance",
  },
  {
    id: 10,
    ctc: "900000",
    salaryPerMonth: "75000",
    deduction: "14000",
    status: "pending",
    name: "Emma Adams",
    avatar: "https://i.pravatar.cc/150?img=5",
    designation: "Operations Manager",
    department: "Operations",
    team: "Operations",
  },
  {
    id: 11,
    ctc: "950000",
    salaryPerMonth: "79166",
    deduction: "15000",
    status: "completed",
    name: "Brandon Stevens",
    avatar: "https://i.pravatar.cc/150?img=8",
    designation: "Junior Developer",
    department: "Engineering",
    team: "Development",
  },
  {
    id: 12,
    ctc: "1000000",
    salaryPerMonth: "83333",
    deduction: "16000",
    status: "pending",
    name: "Megan Richards",
    avatar: "https://i.pravatar.cc/150?img=10",
    designation: "Product Manager",
    department: "Product",
  },
  {
    id: 13,
    ctc: "1050000",
    salaryPerMonth: "87500",
    deduction: "17000",
    status: "completed",
    name: "Oliver Scott",
    avatar: "https://i.pravatar.cc/150?img=11",
    designation: "Security Manager",
    department: "Security",
    team: "Security",
  },
  {
    id: 14,
    ctc: "1100000",
    salaryPerMonth: "91666",
    deduction: "18000",
    status: "pending",
    name: "Sophia Turner",
    avatar: "https://i.pravatar.cc/150?img=12",
    designation: "Support Specialist",
    department: "Support",
    team: "Support",
  },
  {
    id: 15,
    ctc: "1150000",
    salaryPerMonth: "95833",
    deduction: "19000",
    status: "completed",
    name: "John Doe",
    avatar: "https://i.pravatar.cc/150?img=13",
    designation: "Analyst",
    department: "Research",
    team: "Analysis",
  },
  {
    id: 16,
    ctc: "1200000",
    salaryPerMonth: "100000",
    deduction: "20000",
    status: "pending",
    name: "Jane Doe",
    avatar: "https://i.pravatar.cc/150?img=14",
    designation: "Consultant",
    department: "Consulting",
    team: "Advisory",
  },
];

export const holidayColumn = [
  {
    name: "Date",
    uid: "date",
    sortable: true,
  },
  {
    name: "Day",
    uid: "day",
  },
  {
    name: "Holiday Name",
    uid: "name",
  },
  {
    name: "Status",
    uid: "status",
  },
];

export const myTaskColumn = [
  {
    name : "No.",
    uid: "serialNumber",
    sortable: true,
  },
  {
    name: "Task Name",
    uid: "taskName",
    main : true,
    sortable: true,
  },
  {
    name: "Status",
    uid: "status",
  },
  {
    name: "Project",
    uid: "project",
  },
  {
    name: "Assignee",
    uid: "assignee",
  },
  {
    name: "Due Date",
    uid: "dueDate",
  },
  {
    name: "Priority",
    uid: "priority",
    status: true,
  },
  {
    name: "Created At",
    uid: "createdAt",
  },
  {
    name: "Updated At",
    uid: "updatedAt",
  },
  {
    name: "Reporter",
    uid: "reporter",
  },
];

export const myTaskData = [
  {
    serialNumber: 1,
    taskName: "Design Homepage",
    status: "inProgress",
    project: "Website Redesign",
    assignee: "Alice Johnson",
    dueDate: "2024-10-25",
    priority: "high",
    createdAt: "2024-10-01",
    updatedAt: "2024-10-20",
    reporter: "Bob Smith",
  },
  {
    serialNumber: 2,
    taskName: "Develop Login Feature",
    status: "inReview",
    project: "Mobile App",
    assignee: "John Doe",
    dueDate: "2024-10-15",
    priority: "medium",
    createdAt: "2024-09-20",
    updatedAt: "2024-10-15",
    reporter: "Jane Doe",
  },
  {
    serialNumber: 3,
    taskName: "Test Payment Gateway",
    status: "inProgress",
    project: "E-commerce Platform",
    assignee: "Emily Davis",
    dueDate: "2024-10-30",
    priority: "high",
    createdAt: "2024-10-05",
    updatedAt: "2024-10-18",
    reporter: "Michael Brown",
  },
  {
    serialNumber: 4,
    taskName: "Write User Documentation",
    status: "done",
    project: "Software Release",
    assignee: "Chris Lee",
    dueDate: "2024-11-01",
    priority: "low",
    createdAt: "2024-10-10",
    updatedAt: "2024-10-21",
    reporter: "Sarah Wilson",
  },
  {
    serialNumber: 5,
    taskName: "Optimize Database",
    status: "todo",
    project: "Backend Improvement",
    assignee: "David Kim",
    dueDate: "2024-10-20",
    priority: "medium",
    createdAt: "2024-09-25",
    updatedAt: "2024-10-20",
    reporter: "Laura Martinez",
  },
  {
    serialNumber: 6,
    taskName: "Create Marketing Plan",
    status: "draft",
    project: "Product Launch",
    assignee: "Olivia Taylor",
    dueDate: "2024-11-05",
    priority: "high",
    createdAt: "2024-10-15",
    updatedAt: "2024-10-22",
    reporter: "James Anderson",
  },
  {
    serialNumber: 7,
    taskName: "Implement Security Features",
    status: "inProgress",
    project: "System Upgrade",
    assignee: "Sophia Lee",
    dueDate: "2024-10-28",
    priority: "high",
    createdAt: "2024-10-05",
    updatedAt: "2024-10-21",
    reporter: "Daniel Harris",
  },
  {
    serialNumber: 8,
    taskName: "Conduct User Interviews",
    status: "inReview",
    project: "UX Research",
    assignee: "Liam Martinez",
    dueDate: "2024-10-27",
    priority: "medium",
    createdAt: "2024-10-10",
    updatedAt: "2024-10-20",
    reporter: "Emma Clark",
  },
  {
    serialNumber: 9,
    taskName: "Fix Bugs in Module A",
    status: "todo",
    project: "Bug Fixing",
    assignee: "Noah Walker",
    dueDate: "2024-10-29",
    priority: "high",
    createdAt: "2024-10-12",
    updatedAt: "2024-10-22",
    reporter: "Mia Robinson",
  },
  {
    serialNumber: 10,
    taskName: "Prepare Financial Report",
    status: "done",
    project: "Quarterly Review",
    assignee: "Ava Lewis",
    dueDate: "2024-10-20",
    priority: "medium",
    createdAt: "2024-09-30",
    updatedAt: "2024-10-20",
    reporter: "Ethan Young",
  },
  {
    serialNumber: 11,
    taskName: "Set Up CI/CD Pipeline",
    status: "inProgress",
    project: "DevOps",
    assignee: "Isabella King",
    dueDate: "2024-10-26",
    priority: "high",
    createdAt: "2024-10-08",
    updatedAt: "2024-10-21",
    reporter: "Lucas Scott",
  },
  {
    serialNumber: 12,
    taskName: "Design New Logo",
    status: "draft",
    project: "Brand Refresh",
    assignee: "Mason Green",
    dueDate: "2024-11-10",
    priority: "low",
    createdAt: "2024-10-18",
    updatedAt: "2024-10-22",
    reporter: "Charlotte Adams",
  },
  {
    serialNumber: 13,
    taskName: "Plan Team Building Event",
    status: "todo",
    project: "HR Activities",
    assignee: "Amelia Baker",
    dueDate: "2024-11-15",
    priority: "medium",
    createdAt: "2024-10-20",
    updatedAt: "2024-10-22",
    reporter: "Henry Nelson",
  },
  {
    serialNumber: 14,
    taskName: "Update Privacy Policy",
    status: "inReview",
    project: "Compliance",
    assignee: "Harper Carter",
    dueDate: "2024-10-31",
    priority: "high",
    createdAt: "2024-10-01",
    updatedAt: "2024-10-21",
    reporter: "Jack Mitchell",
  },
  {
    serialNumber: 15,
    taskName: "Conduct Code Review",
    status: "inProgress",
    project: "Code Quality",
    assignee: "Ella Perez",
    dueDate: "2024-10-24",
    priority: "medium",
    createdAt: "2024-10-12",
    updatedAt: "2024-10-22",
    reporter: "Alexander Roberts",
  },
];



export const myTaskOptions = [
  { name: "TO DO", uid: "todo", color: "default" },
  { name: "DRAFT", uid: "draft", color: "secondary" },
  { name: "IN PROGRESS", uid: "inProgress", color: "primary" },
  { name: "IN REVIEW", uid: "inReview", color: "warning" },
  { name: "DONE", uid: "done", color: "success" },
  { name : "High" , uid : "high" , color : "danger"}, 
  { name : "Medium" , uid : "medium" , color : "warning"}, 
  { name : "Low" , uid : "low" , color : "primary"}
];

export const holidayOptions = [
  { name: "Past Holidays", uid: "pastHoliday", color: "default" },
  { name: "Upcoming", uid: "upcoming", color: "success" },
];

const today = new Date();

export const holidayData = [
  {
    id: 1,
    date: "January 01, 2024",
    day: "Monday",
    name: "New Year's Day",
    status: new Date("January 01, 2024") > today ? "upcoming" : "pastHoliday",
  },
  {
    id: 2,
    date: "January 26, 2024",
    day: "Friday",
    name: "Republic Day",
    status: new Date("January 26, 2024") > today ? "upcoming" : "pastHoliday",
  },
  {
    id: 3,
    date: "March 29, 2024",
    day: "Friday",
    name: "Holi",
    status: new Date("March 29, 2024") > today ? "upcoming" : "pastHoliday",
  },
  {
    id: 4,
    date: "April 10, 2024",
    day: "Wednesday",
    name: "Ram Navami",
    status: new Date("April 10, 2024") > today ? "upcoming" : "pastHoliday",
  },
  {
    id: 5,
    date: "April 14, 2024",
    day: "Sunday",
    name: "Dr. Ambedkar Jayanti",
    status: new Date("April 14, 2024") > today ? "upcoming" : "pastHoliday",
  },
  {
    id: 6,
    date: "April 19, 2024",
    day: "Friday",
    name: "Good Friday",
    status: new Date("April 19, 2024") > today ? "upcoming" : "pastHoliday",
  },
  {
    id: 7,
    date: "May 01, 2024",
    day: "Wednesday",
    name: "Labour Day",
    status: new Date("May 01, 2024") > today ? "upcoming" : "pastHoliday",
  },
  {
    id: 8,
    date: "August 15, 2024",
    day: "Thursday",
    name: "Independence Day",
    status: new Date("August 15, 2024") > today ? "upcoming" : "pastHoliday",
  },
  {
    id: 9,
    date: "October 02, 2024",
    day: "Wednesday",
    name: "Gandhi Jayanti",
    status: new Date("October 02, 2024") > today ? "upcoming" : "pastHoliday",
  },
  {
    id: 10,
    date: "October 11, 2024",
    day: "Friday",
    name: "Dussehra",
    status: new Date("October 11, 2024") > today ? "upcoming" : "pastHoliday",
  },
  {
    id: 11,
    date: "October 31, 2024",
    day: "Thursday",
    name: "Diwali",
    status: new Date("October 31, 2024") > today ? "upcoming" : "pastHoliday",
  },
  {
    id: 12,
    date: "November 01, 2024",
    day: "Friday",
    name: "Diwali (Bali Pratipada)",
    status: new Date("November 01, 2024") > today ? "upcoming" : "pastHoliday",
  },
  {
    id: 13,
    date: "December 25, 2024",
    day: "Wednesday",
    name: "Christmas",
    status: new Date("December 25, 2024") > today ? "upcoming" : "pastHoliday",
  },
];

