export const sideBarLinks = [
  {
    title: "Dashboard",
    icon: "LayoutDashboard",
    link: "/",
  },
  {
    title: "Employees",
    icon: "Contact",
    link: "/all-employees",
  },
  {
    title: "Departments",
    icon: "Table",
    link: "/departments",
  },
  {
    title: "Attendance",
    icon: "FileChartColumn",
    link: "/attendance",
  },
  {
    title: "Payroll",
    icon: "CircleDollarSign",
    link: "/payroll",
  },
  {
    title: "Jobs",
    icon: "Box",
    link: "/jobs",
  },
  {
    title: "Candidates",
    icon: "CalendarRange",
    link: "/candidates",
  },

  {
    title: "Leaves",
    icon: "BriefcaseBusiness",
    link: "/leaves",
  },
  {
    title: "Holidays",
    icon: "CalendarCheck2",
    link: "/holidays",
  },
  {
    title: "Settings",
    icon: "Settings",
    link: "/settings",
  },
];

export const notificationData = [
  {
    name: "Ralph Edwards",
    time: "2 min Ago.",
    order: "Ordered 3 meals and 1 drink.",
    image: "/bag-happy.png",
    unread: true,
    items: [
      {
        quantity: "1x",
        name: "Fish and Chips with sausage vegetarian",
        price: "$12.00",
      },
      {
        quantity: "1x",
        name: "Fish and Chips with sausage vegetarian",
        price: "$12.00",
      },
      {
        quantity: "1x",
        name: "Fish and Chips with sausage vegetarian",
        price: "$12.00",
      },
    ],
  },
  {
    name: "Ralph Edwards",
    time: "2 min Ago.",
    order: "Ordered 3 meals and 1 drink.",
    image: "/clipboard-close.png",
    unread: true,
    items: [
      {
        quantity: "1x",
        name: "Fish and Chips with sausage vegetarian",
        price: "$12.00",
      },
      {
        quantity: "1x",
        name: "Fish and Chips with sausage vegetarian",
        price: "$12.00",
      },
      {
        quantity: "1x",
        name: "Fish and Chips with sausage vegetarian",
        price: "$12.00",
      },
    ],
  },
  {
    name: "Ralph Edwards",
    time: "2 min Ago.",
    order: "Ordered 3 meals and 1 drink.",
    image: "/bag-happy.png",
    unread: false,
    items: [
      {
        quantity: "1x",
        name: "Fish and Chips with sausage vegetarian",
        price: "$12.00",
      },
      {
        quantity: "1x",
        name: "Fish and Chips with sausage vegetarian",
        price: "$12.00",
      },
      {
        quantity: "1x",
        name: "Fish and Chips with sausage vegetarian",
        price: "$12.00",
      },
    ],
  },
  {
    name: "Ralph Edwards",
    time: "2 min Ago.",
    order: "Ordered 3 meals and 1 drink.",
    image: "/bag-happy.png",
    unread: false,
    items: [
      {
        quantity: "1x",
        name: "Fish and Chips with sausage vegetarian",
        price: "$12.00",
      },
      {
        quantity: "1x",
        name: "Fish and Chips with sausage vegetarian",
        price: "$12.00",
      },
      {
        quantity: "1x",
        name: "Fish and Chips with sausage vegetarian",
        price: "$12.00",
      },
    ],
  },
];

export const statsData = [
  {
    title: "Total Employee",
    amount: 560,
    orders: 28,
    percentage: 28,
    icon: "Contact",
    bgColor: "primary-50",
    lastUpdated: "July 14 , 2023",
  },
  {
    title: "Total Departments",
    amount: 10,
    orders: 10,
    percentage: -28,
    icon: "Table",
    bgColor: "warning-100",
    lastUpdated: "July 14 , 2023",
  },
  {
    title: "Today Attendance",
    amount: 20,
    orders: 14,
    percentage: 56,
    icon: "FileChartColumn",
    bgColor: "default-100",
    lastUpdated: "July 14 , 2023",
  },
  {
    title: "Total Payroll",
    amount: 28033,
    orders: 16,
    percentage: -10,
    icon: "CircleDollarSign",
    bgColor: "success-100",
    lastUpdated: "July 14 , 2023",
  },
];

export const columns = [
  { name: "ID", uid: "id", sortable: true },
  { name: "Employee Name", uid: "name", sortable: true },
  { name: "Department", uid: "department", sortable: true },
  { name: "Designation", uid: "designation", sortable: true },
  { name: "Job Type", uid: "jobType" },
  { name: "Status", uid: "status", sortable: true },
  { name: "Actions", uid: "actions" },
];

export const statusOptions = [
  { name: "Permanent", uid: "permanent", color: "primary" },
  { name: "Intern", uid: "intern", color: "success" },
  { name: "Notice Period", uid: "notice-period", color: "danger" },
];

export const users = [
  {
    id: 1,
    name: "Tony Reichert",
    role: "CEO",
    team: "Management",
    status: "permanent",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
    department: "Executive",
    designation: "Chief Executive Officer",
    jobType: "in-office",
  },
  {
    id: 2,
    name: "Zoey Lang",
    role: "Tech Lead",
    team: "Development",
    status: "intern",
    age: "25",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "zoey.lang@example.com",
    department: "Engineering",
    designation: "Technical Lead",
    jobType: "remote",
  },
  {
    id: 3,
    name: "Jane Fisher",
    role: "Sr. Dev",
    team: "Development",
    status: "permanent",
    age: "22",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "jane.fisher@example.com",
    department: "Engineering",
    designation: "Senior Developer",
    jobType: "hybrid",
  },
  {
    id: 4,
    name: "William Howard",
    role: "C.M.",
    team: "Marketing",
    status: "notice-period",
    age: "28",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    email: "william.howard@example.com",
    department: "Marketing",
    designation: "Campaign Manager",
    jobType: "in-office",
  },
  {
    id: 5,
    name: "Kristen Copper",
    role: "S. Manager",
    team: "Sales",
    status: "permanent",
    age: "24",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "kristen.cooper@example.com",
    department: "Sales",
    designation: "Sales Manager",
    jobType: "remote",
  },
  {
    id: 6,
    name: "Brian Kim",
    role: "P. Manager",
    team: "Management",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "brian.kim@example.com",
    status: "permanent",
    department: "Project Management",
    designation: "Project Manager",
    jobType: "hybrid",
  },
  {
    id: 7,
    name: "Michael Hunt",
    role: "Designer",
    team: "Design",
    status: "intern",
    age: "27",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
    email: "michael.hunt@example.com",
    department: "Creative",
    designation: "Graphic Designer",
    jobType: "remote",
  },
  {
    id: 8,
    name: "Samantha Brooks",
    role: "HR Manager",
    team: "HR",
    status: "permanent",
    age: "31",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
    email: "samantha.brooks@example.com",
    department: "Human Resources",
    designation: "Human Resources Manager",
    jobType: "in-office",
  },
  {
    id: 9,
    name: "Frank Harrison",
    role: "F. Manager",
    team: "Finance",
    status: "notice-period",
    age: "33",
    avatar: "https://i.pravatar.cc/150?img=4",
    email: "frank.harrison@example.com",
    department: "Finance",
    designation: "Finance Manager",
    jobType: "hybrid",
  },
  {
    id: 10,
    name: "Emma Adams",
    role: "Ops Manager",
    team: "Operations",
    status: "permanent",
    age: "35",
    avatar: "https://i.pravatar.cc/150?img=5",
    email: "emma.adams@example.com",
    department: "Operations",
    designation: "Operations Manager",
    jobType: "in-office",
  },
  {
    id: 11,
    name: "Brandon Stevens",
    role: "Jr. Dev",
    team: "Development",
    status: "permanent",
    age: "22",
    avatar: "https://i.pravatar.cc/150?img=8",
    email: "brandon.stevens@example.com",
    department: "Engineering",
    designation: "Junior Developer",
    jobType: "remote",
  },
  {
    id: 12,
    name: "Megan Richards",
    role: "P. Manager",
    team: "Product",
    status: "intern",
    age: "28",
    avatar: "https://i.pravatar.cc/150?img=10",
    email: "megan.richards@example.com",
    department: "Product",
    designation: "Product Manager",
    jobType: "hybrid",
  },
  {
    id: 13,
    name: "Oliver Scott",
    role: "S. Manager",
    team: "Security",
    status: "permanent",
    age: "37",
    avatar: "https://i.pravatar.cc/150?img=12",
    email: "oliver.scott@example.com",
    department: "Security",
    designation: "Security Manager",
    jobType: "in-office",
  },
  {
    id: 14,
    name: "Grace Allen",
    role: "M. Specialist",
    team: "Marketing",
    status: "permanent",
    age: "30",
    avatar: "https://i.pravatar.cc/150?img=16",
    email: "grace.allen@example.com",
    department: "Marketing",
    designation: "Marketing Specialist",
    jobType: "remote",
  },
  {
    id: 15,
    name: "Noah Carter",
    role: "IT Specialist",
    team: "I. Technology",
    status: "intern",
    age: "31",
    avatar: "https://i.pravatar.cc/150?img=15",
    email: "noah.carter@example.com",
    department: "Information Technology",
    designation: "IT Specialist",
    jobType: "hybrid",
  },
  {
    id: 16,
    name: "Ava Perez",
    role: "Manager",
    team: "Sales",
    status: "permanent",
    age: "29",
    avatar: "https://i.pravatar.cc/150?img=20",
    email: "ava.perez@example.com",
    department: "Sales",
    designation: "Sales Manager",
    jobType: "in-office",
  },
  {
    id: 17,
    name: "Liam Johnson",
    role: "Data Analyst",
    team: "Analysis",
    status: "permanent",
    age: "28",
    avatar: "https://i.pravatar.cc/150?img=33",
    email: "liam.johnson@example.com",
    department: "Data Analysis",
    designation: "Data Analyst",
    jobType: "remote",
  },
  {
    id: 18,
    name: "Sophia Taylor",
    role: "QA Analyst",
    team: "Testing",
    status: "permanent",
    age: "27",
    avatar: "https://i.pravatar.cc/150?img=29",
    email: "sophia.taylor@example.com",
    department: "Quality Assurance",
    designation: "QA Analyst",
    jobType: "hybrid",
  },
  {
    id: 19,
    name: "Lucas Harris",
    role: "Administrator",
    team: "Information Technology",
    status: "intern",
    age: "32",
    avatar: "https://i.pravatar.cc/150?img=50",
    email: "lucas.harris@example.com",
    department: "Information Technology",
    designation: "System Administrator",
    jobType: "in-office",
  },
  {
    id: 20,
    name: "Mia Robinson",
    role: "Coordinator",
    team: "Operations",
    status: "permanent",
    age: "26",
    avatar: "https://i.pravatar.cc/150?img=45",
    email: "mia.robinson@example.com",
    department: "Operations",
    designation: "Operations Coordinator",
    jobType: "remote",
  },
];

export const tab = [
  {
    title: "Personal Information",
    icon: "ContactRound",
  },
  {
    title: "Professional Information",
    icon: "BriefcaseBusiness",
  },
  {
    title: "Documents",
    icon: "FolderClosed",
  },
  {
    title: "Account Access",
    icon: "LockKeyholeOpen",
  },
];

export const personalField = [
  {
    id : "firstName",
    title: "First Name",
    type: "text",
  },
  {
    id : "lastName",
    title: "Last Name",
    type: "text",
  },
  {
    id : "email",
    title: "Email Address",
    type: "email",
  },
  {
    id : "phone",
    title: "Phone",
    type: "number",
  },
  {
    id : "dob",
    title: "Date of Birth",
    type: "date",
  },
  {
    id : "address",
    title: "Address",
    type: "text",
  },
  {
    id : "city",
    title: "City",
    type: "text",
  },
  {
    id : "state",
    title: "State",
    type: "text",
  },
  {
    id : "zip",
    title: "Zip Code",
    type: "number",
  },
  {
    id : "maritaltatus",
    title: "Marital Status",
    type: "dropdown",
    data: ["Single", "Married", "Divorced"],
  },
  {
    id : "gender",
    title: "Gender",
    type: "dropdown",
    data: ["Male", "Female"],
  },
  {
    id : "nationality",
    title: "Nationality",
    type: "dropdown",
    data: ["Indian", "American", "Canadian"],
  },
];

export const professionalField = [
  {
    id: "employeeId",
    title: "Employee ID",
    type: "number",
  },
  {
    id: "username",
    title: "User Name",
    type: "text",
  },
  {
    id: "employeeType",
    title: "Employee Type",
    type: "dropdown",
    data: ["Permanent", "Intern", "Notice Period"],
  },
  {
    id: "email",
    title: "Email Address",
    type: "email",
  },
  {
    id: "department",
    title: "Department",
    type: "dropdown",
    data: [
      "Engineering",
      "Marketing",
      "Sales",
      "Human Resources",
      "Finance",
      "Operations",
      "Creative",
      "Product",
      "Security",
      "Information Technology",
    ],
  },
  {
    id: "designation",
    title: "Enter Designation",
    type: "text",
  },
  {
    id: "workingDays",
    title: "Working Days",
    type: "dropdown",
    data: ["Monday to Friday", "Monday to Saturday", "Monday to Sunday"],
  },
  {
    id: "joiningDate",
    title: "Joining Date",
    type: "date",
  },
  {
    id: "jobType",
    title: "Job Type",
    type: "dropdown",
    data: ["In-Office", "Remote", "Hybrid"],
  },
  {
    id: "reportingManager",
    title: "Reporting Manager",
    type: "dropdown",
    data: [
      "Tony Reichert",
      "Zoey Lang",
      "Jane Fisher",
      "William Howard",
      "Kristen Copper",
      "Brian Kim",
      "Michael Hunt",
      "Samantha Brooks",
      "Frank Harrison",
      "Emma Adams",
      "Brandon Stevens",
      "Megan Richards",
      "Oliver Scott",
      "Grace Allen",
      "Noah Carter",
      "Ava Perez",
      "Liam Johnson",
      "Sophia Taylor",
      "Lucas Harris",
      "Mia Robinson",
    ],
  },
  {
    id: "officeLocation",
    title: "Office Location",
    type: "dropdown",
    data: [
      "New York",
      "Los Angeles",
      "Chicago",
      "Houston",
      "Phoenix",
      "Philadelphia",
      "San Antonio",
      "San Diego",
      "Dallas",
      "San Jose",
      "Austin",
      "Jacksonville",
      "Fort Worth",
      "Columbus",
      "Charlotte",
      "Indianapolis",
      "San Francisco",
      "Seattle",
      "Denver",
      "Washington",
    ],
  },
];

export const socialField = [
  {
    id : "instagram",
    title: "Instagram",
    type: "text",
  },
  {
    id : "twitter",
    title: "Twitter",
    type: "text",
  },
  {
    id : "linkedin",
    title: "LinkedIn",
    type: "text",
  },
  {
    id : "github",
    title: "Github",
    type: "text",
  },
];
